#index:
#    path: /
#    controller: App\Controller\DefaultController::index

register:
  path: /users
  controller: App\Controller\AuthController::register
  methods: POST

#api_login_check:
 # path: /sessions
#  controller: App\Controller\AuthController::getTokenUser
 # methods: POST

login:
  path: /sessions
  controller: App\Controller\AuthController::login
  methods: POST

createRental:
  path: /rentals
  controller: App\Controller\CarrentalsController::createRental
  methods: ['POST', 'GET']

  
addCar:
  path: /cars
  controller: App\Controller\CarrentalsController::cars
  methods: ['POST', 'GET']

test:
  path: /api/test
  controller: App\Controller\ApiController::test
